#!/bin/bash

set -e
set -o pipefail

usage() {
  echo "Usage: git-autosave <command> [options]"
  echo ""
  echo "Commands:"
  echo "  start               Start watching the current directory for changes"
  echo "  list                List all autosaved states"
  echo "  show <hash>         Show the diff of the given autosaved state and HEAD"
  echo "  restore <hash>      Resets HEAD to the given state"
  echo "  save-working-dir    Save the current working directory's state"

  exit 1
}

init() {
  # TODO
  echo 'export PROMPT_COMMAND="pwd"'
  # shellcheck disable=SC2016
  echo 'precmd() { eval "$PROMPT_COMMAND" }'
}

start() {
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    exit 0
  fi

  if ! git diff --exit-code autosave >/dev/null 2>&1; then
    exit 0
  fi

  # TODO make sure conditions are correct
  #save_working_dir
}

save_working_dir() {
  local ref="refs/autosave"
  local tree_hash
  local parent
  local message
  local commit_hash

  echo "Saving working dir"

  # Create tree
  tree_hash=$(write_tree ".")

  # Create commit
  parent=$(git show-ref --hash "$ref" || true)
  message="Autosave $(date)"
  commit_hash=$(commit_tree "$tree_hash" "$message" "$parent")

  # Create ref
  git update-ref "$ref" "$commit_hash"
}

list() {
  # TODO this should diff with the current working directory not parents
  git log --pretty=short -p autosave
}

show() {
  local hash="$1"

  if [ ! "$hash" ]; then
    usage
  fi

  if ! is_valid_hash "$hash"; then
    echo "Error: Not a valid hash: $hash"
    exit 1
  fi

  # TODO this should diff with the current working directory not HEAD
  git diff "HEAD..$hash"
}

restore() {
  local hash="$1"
  local patch
  local tmp_tree_hash
  local tmp_commit_hash

  if [ ! "$hash" ]; then
    usage
  fi

  if ! is_valid_hash "$hash"; then
    echo "Error: Not a valid hash: $hash"
    exit 1
  fi

  # Create a temporary commit
  tmp_tree_hash=$(write_tree ".")
  tmp_commit_hash=$(commit_tree "$tmp_tree_hash" "Autosave temporary")

  # Create patch
  patch=$(git diff-tree -p "$tmp_commit_hash" "$hash")

  # Apply patch
  echo "Applying patch..."
  echo "$patch"
  git apply <(echo "$patch")
}

commit_tree() {
  local tree_hash="$1"
  local message="$2"
  local parent="$3"

  git commit-tree ${parent:+ -p "$parent"} -m "$message" "$tree_hash"
}

write_tree() {
  local dir="$1"
  local tree=""
  local filename
  local file
  local hash

  for file in $dir/*; do
    filename=$(basename "$file")

    if [ -f "$file" ]; then
      hash=$(git hash-object -w -- "$file")
      # TODO set correct mode
      tree="${tree}100644 blob $hash\t$filename\n"
    elif [ -d "$file" ]; then
      write_tree "$file" 1>/dev/null
    fi
  done

  printf "%b" "$tree" | git mktree
}

is_valid_hash() {
  local hash="$1"

  [ "$(git rev-parse "$hash")" = "$hash" ]
}

if [ $# = 0 ]; then
  usage
fi

cmdname="$1"
shift

case "$cmdname" in
  start)
    start
    ;;
  list)
    list
    ;;
  show)
    show "$@"
    ;;
  restore)
    restore "$@"
    ;;
  save-working-dir)
    save_working_dir
    ;;
  *)
    usage
    ;;
esac
